name: Cypress Tests

on:
  push:
    paths:
      - "packages/cypress/**"
      - ".github/workflows/cypress.yml"
  pull_request:
    paths:
      - "packages/cypress/**"
      - ".github/workflows/cypress.yml"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:22.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm run test:cypress
