name: Playwright Tests

on:
  push:
    paths:
      - "packages/playwright/**"
      - ".github/workflows/playwright.yml"
  pull_request:
    paths:
      - "packages/playwright/**"
      - ".github/workflows/playwright.yml"
  workflow_dispatch:

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.2-noble
      options: --user 1001
    defaults:
      run:
        working-directory: packages/playwright
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
